# name: lint

on:
  push:
    paths-ignore:
      - README.md
  lint:
    runs-on: ubuntu-latest
    container: ubuntu:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run ShellCheck
        uses: reviewdog/action-shellcheck@v1
        env:
          shellcheck_flags: --exclude=SC1090